batch_size: 128
dropout: 0.7
lr: 0.0008
lr_final: 6.918309709189366e-07
model_name: EEGNeX
random_seed: 42
releases_train:
- R12
target_name: attention
tasks:
- contrastChangeDetection
train_epochs: 150
