batch_size: 128
dropout: 0.7
lr: 0.0008
lr_final: 3.0199517204020163e-06
model_name: EEGNeX
random_seed: 42
releases_train:
- R12
target_name: attention
tasks:
- contrastChangeDetection
train_epochs: 150
