batch_size: 128
dropout: 0.7
lr: 0.0008
lr_final: 0.0003019951720402019
model_name: EEGNeX
random_seed: 42
releases_train:
- R12
target_name: attention
tasks:
- contrastChangeDetection
train_epochs: 150
