name: Fetch OpenNeuro Datasets

on:
  schedule:
    # Run weekly on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  fetch-datasets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gql[requests]

      - name: Fetch OpenNeuro datasets
        env:
          OPENNEURO_TOKEN: ${{ secrets.OPENNEURO_TOKEN }}
        run: |
          python scripts/ingestions/fetch_openneuro_datasets.py \
            --page-size 100 \
            --output consolidated/openneuro_datasets.json

      - name: Verify output
        run: |
          if [ -f consolidated/openneuro_datasets.json ]; then
            echo "✓ Dataset file created successfully"
            python -c "import json; data = json.load(open('consolidated/openneuro_datasets.json')); print(f'Total entries: {len(data)}'); modalities = set(d['modality'] for d in data); print(f'Modalities: {sorted(modalities)}')"
          else
            echo "✗ Dataset file not created"
            exit 1
          fi

      - name: Commit changes if datasets updated
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'chore: update OpenNeuro dataset listings'
          add: 'consolidated/openneuro_datasets.json'
          pull: '--rebase --autostash'
          push: true
        if: always()

      - name: Upload artifacts for downstream jobs
        uses: actions/upload-artifact@v4
        with:
          name: openneuro-datasets
          path: consolidated/openneuro_datasets.json
          retention-days: 7
